# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170717_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_time']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='pub_time',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
